import type { NextPage } from "next";
import { useRouter } from 'next/router'

import { useEffect, useState } from 'react';
import Head from "next/head";
import Image from "next/image";
import { Container, Title, Button, Space, Group } from "@mantine/core";
import styles from "../styles/Home.module.css";
import { Navbar, Banner } from "../components";
import { supabase } from "../utils/supabase";
import { Profile } from "../types";

const Dashboard: NextPage = () => {
  const router = useRouter();
  console.log('USER OBJ HERE', supabase.auth.user())

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar title={"find-a-coach 🏃‍♀️"} />
        <Space h="xl" />
        <h1>Form goes here</h1>
      </main>
    </Container>
  );
};

export default Dashboard;
