import type { InferGetServerSidePropsType, NextPage } from "next";
import { useRouter } from "next/router";

import { useEffect, useState } from "react";
import Head from "next/head";
import { Container, Title, Button, Space, Group } from "@mantine/core";
import { Navbar, Banner } from "../components";
import { supabase } from "../utils/supabase";
import { ClientList } from "../components";
import { FitDistanceTile } from "../components/FitDistanceTile";
import { useUser } from '../hooks/useUser';
const Dashboard: NextPage = () => {
  const router = useRouter();
  const [setUser] = useUser((state) => [state.setUser]);

  useEffect(() => {
    setTimeout(
    (async () => {
      const user = supabase.auth.user();
      setUser(user)
      console.log('curr user', user)
      let { data: dbProfile, error } = await supabase
        .from("profile")
        .select("*")
        .eq("id", user?.id);
      console.log("👀", dbProfile);

      if (!dbProfile?.length) {
        router.push("/create");
      }
    }), 100)
  }, []);

  // useEffect(() => {
  //   getLastActivity();
  // }, []);

  const getLastActivity = async () => {
    console.log("get last activity");
    const activities = await fetch("/api/garmin-connect");
    const s = await activities.text();
    console.log("🎾", JSON.parse(s));
    return activities;

    // const lastActivity = activities[activities.length - 1]
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar title={"find-a-coach 🏃‍♀️"} />
        <Space h="xl" />
        <ClientList></ClientList>
        <FitDistanceTile distance="30" unit="Km" />
      </main>
    </Container>
  );
};


export default Dashboard;
