import type { NextPage } from "next";
import { useRouter } from 'next/router'

import { useEffect, useState } from 'react';
import Head from "next/head";
import Image from "next/image";
import { Container, Title, Button, Space, Group } from "@mantine/core";
import styles from "../styles/Home.module.css";
import { Navbar, Banner } from "../components";
import { supabase } from "../utils/supabase";
import { Profile } from "../types";

const Dashboard: NextPage = () => {
  const router = useRouter();
  const [profile, setProfile] = useState<Profile>()
  console.log('USER OBJ HERE', supabase.auth.user())
  useEffect(() => {
    (async ()=>{
      const user = supabase.auth.user();
      let { data: dbProfile, error } = await supabase
        .from('profile')
        .select("*")
    
        // Filters
        .eq('id', user?.id)

      console.log('PROFILE?:::', dbProfile)
      if (dbProfile?.length) {
        setProfile(dbProfile[0]);
      } else {
        router.push('/create')
      }
    })()
  }, [])
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar title={"find-a-coach 🏃‍♀️"} />
        <Space h="xl" />
        
      </main>
    </Container>
  );
};

export default Dashboard;
