import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container, Title, Button } from "@mantine/core";
import styles from "../styles/Home.module.css";
import { Navbar, Banner } from "../components";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar title={"hello there"} />
        <Banner
          imageSrc="https://images.unsplash.com/photo-1486218119243-13883505764c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2072&q=80"
          title="Hello banner"
        />
      </main>
    </Container>
  );
};

export default Home;
